import type { DeepSearchTask, PluginConfig } from '../types';
type Ctx = any;
export declare class DeepSearchTaskService {
    private readonly ctx;
    private readonly config;
    static readonly EXPIRED_GRACE_MS = 5000;
    private readonly logger;
    private readonly tasks;
    private queue;
    private runningCount;
    private sequence;
    private readonly cleanupTimer;
    private disposed;
    constructor(ctx: Ctx, config: PluginConfig);
    dispose(): void;
    submit(claim: string, session?: any, conversationId?: string): DeepSearchTask;
    getStatus(taskId: string, session?: any): DeepSearchTask | null;
    getResult(taskId: string, session?: any): DeepSearchTask | null;
    private processQueue;
    private executeTask;
    private notifyTaskCompletion;
    private pushToChatlunaConversation;
    private notifyCharacterFallback;
    private buildCompletionMessage;
    private resolveConversationId;
    private cleanupExpiredTasks;
    private generateTaskId;
    private getTaskTimeoutMs;
    private canAccessTask;
    private resolveTaskOwner;
}
export {};
